
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://yrpmseqrxvehahrekcly.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InlycG1zZXFyeHZlaGFocmVrY2x5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDI3NDYyNTMsImV4cCI6MjA1ODMyMjI1M30.hJZD5RW-7xLd0ml7O3Mn8laWnPu3FnTImZwM5uHz5ZA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    persistSession: true,
    autoRefreshToken: true,
    storage: localStorage
  }
});
